language: android
sudo: false
install: true

jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

licenses:
  - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

before_script:
  - android list target

jobs:
  include:
    - stage: compile
      script: ./gradlew assemble
    - stage: deploy
      if: branch = master AND type != pull_request
      script: ./gradlew bintrayUpload

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'